# fly.toml app configuration generated for Echina

app = "echina"
primary_region = "lax"

[build]
builder = "paketobuildpacks"

[[build.buildpacks]]
id = "heroku/nodejs-engine"

[[build.buildpacks]]
id = "heroku/nodejs-npm-build"

[[build.buildpacks]]
id = "heroku/nodejs-npm-start"

[env]
NODE_ENV = "production"

[deploy]
strategy = "bluegreen"
wait_timeout = "300s"

[[services]]
protocol = "tcp"
internal_port = 3001
processes = ["app"]

  [services.concurrency]
  type = "requests"
  hard_limit = 1000
  soft_limit = 800

  [[services.ports]]
  number = 80
  protocol = "tcp"
  handlers = ["http"]

  [[services.ports]]
  number = 443
  protocol = "tcp"
  handlers = ["tls", "http"]

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[vm]]
memory = "512mb"
cpus = 1
