Starting to scrape 33 URLs...
Successfully scraped 33 products.
Total successful products: 33
Generating SQL insert...
---SQL_START---
INSERT INTO supplier_products (title, image_url, price_min, price_max, moq, description, supplier_name, alibaba_link, category, status) VALUES 
('2025 Clearance Price Women Dress Bale Mixes Clothes Bulk Assorted Brand Used Clothes Women Apparel Stock Clothing', 'https://s.alicdn.com/@sc04/kf/H50a3433dfaa744bb857f07dcb600fa66L.jpg_720x720Q50.jpg', 152, 1497, 1, '2025 Clearance Price Women Dress Bale Mixes Clothes Bulk Assorted Brand Used Clothes Women Apparel Stock Clothing. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · HK · HK BAODEYOU INDUSTRIA LIMITED', 'https://www.alibaba.com/x/1lAevq6?ck=pdp', 'electronics', 'active'),
('Top New Oval Digital LED Electronic Watch Bracelet Waterproof Fashion Simple Sports for Man Women Children Students', 'https://s.alicdn.com/@sc04/kf/H456d90f50de34c81ab2578494d20e90bB.jpg_720x720Q50.jpg', 454, 499, 15, 'Top New Oval Digital LED Electronic Watch Bracelet Waterproof Fashion Simple Sports for Man Women Children Students. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Yunfu Jiashengxin Clock Co., Ltd.', 'https://www.alibaba.com/x/1lAevdS?ck=pdp', 'watches', 'active'),
('Stock Apparel Factory Direct Dress Short Sleeve Skirt Pants Suspender Vest T-shirt Mixed Bulk Clothes Bales Used Clothes', 'https://s.alicdn.com/@sc04/kf/H432f6db0832e431484d3ff89af2145510.png_720x720.png', 288, 1497, 2, 'Stock Apparel Factory Direct Dress Short Sleeve Skirt Pants Suspender Vest T-shirt Mixed Bulk Clothes Bales Used Clothes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '2 yrs · CN · Fuzhou Gulou District Mingming Jiayuan Import and Export Co., Ltd.', 'https://www.alibaba.com/x/1lAevRS?ck=pdp', 'men's shorts', 'active'),
('Custom logo Student Electronic Fashion Sports Watch Child LED Watch Kids Digital Luxury Watches', 'https://s.alicdn.com/@sc04/kf/Hb95c971c11da4194b54f60e7fc136af3f.jpg_720x720Q50.jpg', 650, 681, 5, 'Custom logo Student Electronic Fashion Sports Watch Child LED Watch Kids Digital Luxury Watches. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Yunfu Jiashengxin Clock Co., Ltd.', 'https://www.alibaba.com/x/1lAevRY?ck=pdp', 'watches', 'active'),
('Wholesale Customized Men''s Thermal Fitness Sweatsuit Long Sleeve Jogger Training Suits Hot Sale Print Tracksuits For Winter', 'https://s.alicdn.com/@sc04/kf/H0ffe20ab12664ba58f087f5dd3a723dam.jpg_720x720Q50.jpg', 711, 4822, 100, 'Wholesale Customized Men''s Thermal Fitness Sweatsuit Long Sleeve Jogger Training Suits Hot Sale Print Tracksuits For Winter. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Guangzhou Jianling Clothing Import And Export Co., Ltd.', 'https://www.alibaba.com/x/1lAew0M?ck=pdp', 'shirt long sleeves', 'active'),
('Custom Logo Wholesale Cheap Elastic Band Bonnet De Perruque Sleeping Silk Hair Bonnet Customable Femme Women Satin Bonnets', 'https://s.alicdn.com/@sc04/kf/He59ccb8249d940d59634afcfa1dd32afq.jpg_720x720Q50.jpg', 590, 666, 5, 'Custom Logo Wholesale Cheap Elastic Band Bonnet De Perruque Sleeping Silk Hair Bonnet Customable Femme Women Satin Bonnets. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Yiwu Kerong Trading Co., Ltd.', 'https://www.alibaba.com/x/1lAew0U?ck=pdp', 'electronics', 'active'),
('JX Wholesale Custom Logo Sports Fishing Image Full Face Cover Ski Mask Balaclava Cap 100% Polyester Unisex', 'https://s.alicdn.com/@sc04/kf/Hd2e15c78bc454b9299b82e2190e659c1Y.jpg_720x720Q50.jpg', 560, 1059, 5, 'JX Wholesale Custom Logo Sports Fishing Image Full Face Cover Ski Mask Balaclava Cap 100% Polyester Unisex. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Xiamen Jiang Xi E-Commerce Co., Ltd.', 'https://www.alibaba.com/x/1lAew0m?ck=pdp', 'electronics', 'active'),
('Fashion Black Men''s Arabic Dial Quartz Watch for Man Gift Wholesale Custom Wrist Watches Montre Arabe Pour Homme', 'https://s.alicdn.com/@sc04/kf/H5a60abc4cc1049aaaf1d5ba6153f206dS.jpg_720x720Q50.jpg', 847, 3084, 2, 'Fashion Black Men''s Arabic Dial Quartz Watch for Man Gift Wholesale Custom Wrist Watches Montre Arabe Pour Homme. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '2 yrs · CN · Dongguan Langshi Ni Watch Co., Ltd.', 'https://www.alibaba.com/x/1lAew0u?ck=pdp', 'watches', 'active'),
('Solar Panel Emergency Power Station 100W XT60 QC 18W PD Fast Charging LiFePO4 Battery Power Bank Portable Wireless Charger', 'https://s.alicdn.com/@sc04/kf/Ha09f8941cdc84aef857a0bc8fd9658beZ.png_720x720.png', 40057, 44592, 1, 'Solar Panel Emergency Power Station 100W XT60 QC 18W PD Fast Charging LiFePO4 Battery Power Bank Portable Wireless Charger. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '7 yrs · CN · Shen Zhen Deto Electronic Co., Ltd', 'https://www.alibaba.com/x/1lAewEl?ck=pdp', 'inverters', 'active'),
('Factory Direct Sales Portable Power Station Home Solar Power Generator Energy Storage System', 'https://s.alicdn.com/@sc04/kf/H1273016a91df4cbe82a9fdeaed628833R.jpg_720x720Q50.jpg', 69381, 139064, 20, 'Factory Direct Sales Portable Power Station Home Solar Power Generator Energy Storage System. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '5 yrs · CN · Zhongshan Shouliang Technology Co., Ltd.', 'https://www.alibaba.com/x/1lAewEt?ck=pdp', 'inverters', 'active'),
('Custom High Quality Men''s Baggy Jeans Washed Vintage Nylon Cotton Brand Logo Casual Streetwear Denim Jeans', 'https://s.alicdn.com/@sc04/kf/H4d6c88b1441841e5af0a0216f0dcdb8dK.jpg_720x720Q50.jpg', 3024, 6047, 1, 'Custom High Quality Men''s Baggy Jeans Washed Vintage Nylon Cotton Brand Logo Casual Streetwear Denim Jeans. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '5 yrs · CN · Dongguan Tianan Clothing Co., Ltd.', 'https://www.alibaba.com/x/1lAew16?ck=pdp', 'bags', 'active'),
('Men''s Blue Black Baggy Jeans Straight Loose Micro Wide-leg Mid Waist Solid Baggy Jeans for Men', 'https://s.alicdn.com/@sc04/kf/Hd19185f68fa94115ad48a17a838ea7fev.png_720x720.png', 1361, 19500, 1, 'Men''s Blue Black Baggy Jeans Straight Loose Micro Wide-leg Mid Waist Solid Baggy Jeans for Men. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '2 yrs · CN · Guangzhou Yuexiu District Nanwu Clothing Firm', 'https://www.alibaba.com/x/1lAewF6?ck=pdp', 'bags', 'active'),
('Dropship Round Amoled Screen Watch Smart 2025 Original Waterproof Phone Call Smartwatches for Apples IPhones Samsugs Galaxies', 'https://s.alicdn.com/@sc04/kf/Hde983d1c65e54f37b3cf18374c334c05A.jpg_720x720Q50.jpg', 7332, 8994, 1, 'Dropship Round Amoled Screen Watch Smart 2025 Original Waterproof Phone Call Smartwatches for Apples IPhones Samsugs Galaxies. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '10 yrs · CN · Shenzhen Yoke Electronics Co., Ltd.', 'https://www.alibaba.com/x/1lAewFC?ck=pdp', 'watches', 'active'),
('SENBONO T7 Big Smart Watch 1.83-inch TFT Fitness tracker Heart Rate Sleep Monitoring AI Voice Assistant Wrist IP67 Waterproof', 'https://s.alicdn.com/@sc04/kf/H82f17f68a453473cb9103601310e6e9dD.jpg_720x720Q50.jpg', 11942, 14814, 2, 'SENBONO T7 Big Smart Watch 1.83-inch TFT Fitness tracker Heart Rate Sleep Monitoring AI Voice Assistant Wrist IP67 Waterproof. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '6 yrs · CN · Shenzhen SENBONO Electronic Technology Co., Ltd', 'https://www.alibaba.com/x/1lAew1h?ck=pdp', 'watches', 'active'),
('Women Sandals Square Heel 2025 Summer Shoes Woman Fashion Slides Cut-out Open Toe Slip on Mothers Sandal Female Bling Slippers', 'https://s.alicdn.com/@sc04/kf/H8dcdfffc1f9b484b851142be254d8795H.jpg_720x720Q50.jpg', 983, 1784, 5, 'Women Sandals Square Heel 2025 Summer Shoes Woman Fashion Slides Cut-out Open Toe Slip on Mothers Sandal Female Bling Slippers. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '6 yrs · CN · Yiwu Qibei Import And Export Co., Ltd.', 'https://www.alibaba.com/x/1lAew1v?ck=pdp', 'female shoes', 'active'),
('Hot Sale in the Summer of 2024 the New Bow slippers Were Worn with Korean Flower Sandals and Women''s Flat Shoes', 'https://s.alicdn.com/@sc04/kf/Hd76b3277ca864b60a4c73b959a1aecc12.jpg_720x720Q50.jpg', 681, 923, 2, 'Hot Sale in the Summer of 2024 the New Bow slippers Were Worn with Korean Flower Sandals and Women''s Flat Shoes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Yiwu Xunhan Trading Co., Ltd.', 'https://www.alibaba.com/x/1lAew27?ck=pdp', 'female shoes', 'active'),
('Fashionable Women''s Summer Walking Shoes - Breathable and Comfortable Flat Sole', 'https://s.alicdn.com/@sc04/kf/Ha92d97503abd438cb6c62635b2704f74s.jpg_720x720Q50.jpg', 847, 1436, 3, 'Fashionable Women''s Summer Walking Shoes - Breathable and Comfortable Flat Sole. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '8 yrs · CN · Yiwu Yongge Shoes Co., Ltd.', 'https://www.alibaba.com/x/1lAewFh?ck=pdp', 'electronics', 'active'),
('Manufacturer Summer Height Increasing slippers Short New Style Lazy Fashionable Student Half Flip Flops Slippers for Women', 'https://s.alicdn.com/@sc04/kf/H26df76d9b95e42e0ba47556d40e42e4fl.jpg_720x720Q50.jpg', 1497, 1950, 2, 'Manufacturer Summer Height Increasing slippers Short New Style Lazy Fashionable Student Half Flip Flops Slippers for Women. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '8 yrs · CN · Yiwu Yongge Shoes Co., Ltd.', 'https://www.alibaba.com/x/1lAew2M?ck=pdp', 'men's shorts', 'active'),
('Women Plush Heart Slippers Closed Toe Slippers Non Slip Slip-on House Shoes Comfortable Flat Thermal Slippers for Indoor Bedroom', 'https://s.alicdn.com/@sc04/kf/Hab0ee2230998419d964f8fb25d330f587.jpg_720x720Q50.jpg', 983, 1784, 5, 'Women Plush Heart Slippers Closed Toe Slippers Non Slip Slip-on House Shoes Comfortable Flat Thermal Slippers for Indoor Bedroom. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Jinhua Qi''ancheng Trading Co., Ltd.', 'https://www.alibaba.com/x/1lAewFy?ck=pdp', 'female shoes', 'active'),
('Wholesale Custom Fashion 2025 Design Bathroom Anti-slip Soft Waterproof Quick-drying Women Ladies Shoes Slides Slippers Femme', 'https://s.alicdn.com/@sc04/kf/Hbfe0ef0956834f8283420406e8e89f4fU.jpg_720x720Q50.jpg', 3009, 4369, 2, 'Wholesale Custom Fashion 2025 Design Bathroom Anti-slip Soft Waterproof Quick-drying Women Ladies Shoes Slides Slippers Femme. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Shenzhen Feiyuhang Technology Co., Ltd.', 'https://www.alibaba.com/x/1lAevg2?ck=pdp', 'female shoes', 'active'),
('Comfortable and Breathable Men''s Summer 2025 Retro Loafers Mesh Lining PVC Insole Casual Youth Shoes', 'https://s.alicdn.com/@sc04/kf/H6e97d149e2cf494b881c0e4cbd5792ecI.jpg_720x720Q50.jpg', 5563, 5865, 1, 'Comfortable and Breathable Men''s Summer 2025 Retro Loafers Mesh Lining PVC Insole Casual Youth Shoes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '6 yrs · CN · Luoyang Lingbao Trading Co., Ltd.', 'https://www.alibaba.com/x/1lAevgz?ck=pdp', 'male shoes', 'active'),
('Customizable Text Printed Thick-Soled Men''s Solid Color Clogs, Non-Slip and Wear-Resistant Casual Outdoor Beach Clogs', 'https://s.alicdn.com/@sc04/kf/H037100da2b71465ba02d0c8ac4a78f74T.jpg_720x720Q50.jpg', 3628, 3931, 2, 'Customizable Text Printed Thick-Soled Men''s Solid Color Clogs, Non-Slip and Wear-Resistant Casual Outdoor Beach Clogs. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '6 yrs · CN · Fuzhou Zhongqian Imp.&Exp.', 'https://www.alibaba.com/x/1lAewHC?ck=pdp', 'male shoes', 'active'),
('2025 New Style Fashion Sneakers More Color Shoes Casual Walking Style Shoes for Man Ayakkabi Erkek Chaussures Pour Hommes', 'https://s.alicdn.com/@sc04/kf/H8ed028e5d58647ba9fc78c9591ad7210t.jpg_720x720Q50.jpg', 4989, 5291, 2, '2025 New Style Fashion Sneakers More Color Shoes Casual Walking Style Shoes for Man Ayakkabi Erkek Chaussures Pour Hommes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '4 yrs · CN · Shijiazhuang Hengzhuo Technology Co., Ltd.', 'https://www.alibaba.com/x/1lAew45?ck=pdp', 'male shoes', 'active'),
('Chinese National''s High-top Skateboarding Shoes for Men Trendy All-season Height-increasing Sports Shoes Summer Leisure Original', 'https://s.alicdn.com/@sc04/kf/H8194305f4abd4b3ea3185c8675375c4bC.jpg_720x720Q50.jpg', 6032, 7407, 2, 'Chinese National''s High-top Skateboarding Shoes for Men Trendy All-season Height-increasing Sports Shoes Summer Leisure Original. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Shenzhen Feiyuhang Technology Co., Ltd.', 'https://www.alibaba.com/x/1lAew4M?ck=pdp', 'electronics', 'active'),
('Men''s Business Formal Artificial Leather Shoes Comfort Office Spring Big Size Lightweight Trendy Single Low-Top Wedding Groom', 'https://s.alicdn.com/@sc04/kf/He6482858273345518adaba4d739dd675G.jpg_720x720Q50.jpg', 16945, 19061, 2, 'Men''s Business Formal Artificial Leather Shoes Comfort Office Spring Big Size Lightweight Trendy Single Low-Top Wedding Groom. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Wenzhou Better Outdoor Products Co., Ltd.', 'https://www.alibaba.com/x/1lAew4T?ck=pdp', 'electronics', 'active'),
('2025 New Style Canvas More Color Shoes Casual Walking Style Shoes for Man Ayakkabi Erkek Chaussures Pour Hommes', 'https://s.alicdn.com/@sc04/kf/H1636f99871e94ca69544a81e4b9dcbe46.jpg_720x720Q50.jpg', 2510, 4762, 2, '2025 New Style Canvas More Color Shoes Casual Walking Style Shoes for Man Ayakkabi Erkek Chaussures Pour Hommes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Huangshi International Trade (hainan) Co., Ltd.', 'https://www.alibaba.com/x/1lAevv6?ck=pdp', 'bags', 'active'),
('New Business Formal Dress Men''s Shoes in Korean Style Trendy and Casual with an English Style Touch', 'https://s.alicdn.com/@sc04/kf/H543975c09a9549d2ab3ec116d2a20d5fd.jpg_720x720Q50.jpg', 39301, 54417, 2, 'New Business Formal Dress Men''s Shoes in Korean Style Trendy and Casual with an English Style Touch. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Xiamen Linghang Future Import and Export Co., Ltd.', 'https://www.alibaba.com/x/1lAevvC?ck=pdp', 'electronics', 'active'),
('Men Shoes Pu Leather Casual Men`s Loafers Sneakers Breathable Slip on Boat Italian Dress Shoes for Men', 'https://s.alicdn.com/@sc04/kf/H120850578353496ea955d1afbd1226a3T.jpg_720x720Q50.jpg', 17837, 20860, 1, 'Men Shoes Pu Leather Casual Men`s Loafers Sneakers Breathable Slip on Boat Italian Dress Shoes for Men. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '6 yrs · CN · Jinjiang Micro Sports Goods Co., Ltd.', 'https://www.alibaba.com/x/1lAevvO?ck=pdp', 'male shoes', 'active'),
('Men''s Suede Leather Flat Loafers Round Toe Casual Shoes for Work Holidays High Quality Designer Brand for Winter and Autumn', 'https://s.alicdn.com/@sc04/kf/H807d33fea48e455e99e0e6b3ab54fd3a0.jpg_720x720Q50.jpg', 6803, 7861, 2, 'Men''s Suede Leather Flat Loafers Round Toe Casual Shoes for Work Holidays High Quality Designer Brand for Winter and Autumn. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '9 yrs · CN · Baoding Smart Trading Co., Ltd.', 'https://www.alibaba.com/x/1lAevvX?ck=pdp', 'male shoes', 'active'),
('Men''s Casual PU Upper Business Formal Trendy Comfortable Breathable Shock Absorption Slip-on Solid Color Cross-border New Style', 'https://s.alicdn.com/@sc04/kf/H18110f4e7fed4ae68021fbcaf2ebb43d4.png_720x720.png', 11443, 14768, 1, 'Men''s Casual PU Upper Business Formal Trendy Comfortable Breathable Shock Absorption Slip-on Solid Color Cross-border New Style. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '3 yrs · CN · Ruian Youfu Footwear Co., Ltd.', 'https://www.alibaba.com/x/1lAewUh?ck=pdp', 'electronics', 'active'),
('Men Loafers Large Size Mens Shoes Comfortable And Non Slip Soft Sole Waterproof Leather Surface Casual Pu Leather Shoes', 'https://s.alicdn.com/@sc04/kf/H3d3bb1a5f58347b5ad71d64082867068O.jpg_720x720Q50.jpg', 9705, 10355, 2, 'Men Loafers Large Size Mens Shoes Comfortable And Non Slip Soft Sole Waterproof Leather Surface Casual Pu Leather Shoes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '1 yrs · CN · Yiwu Yuntao Footwear Co., Ltd.', 'https://www.alibaba.com/x/1lAewUo?ck=pdp', 'male shoes', 'active'),
('YATAI Spring Summer Autumn Men''s Lace-Up Fashion Trend Breathable Lightweight Walking Style Sports Sneakers', 'https://s.alicdn.com/@sc04/kf/H4eb4ee8c2344464b8ff6bdf5c6ed53885.jpg_720x720Q50.jpg', 1966, 4233, 1, 'YATAI Spring Summer Autumn Men''s Lace-Up Fashion Trend Breathable Lightweight Walking Style Sports Sneakers. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '5 yrs · CN · Wenxian Yatai Shoes Factory', 'https://www.alibaba.com/x/1lAevvr?ck=pdp', 'male shoes', 'active'),
('Spring and Autumn Latest Fashionable Men''s Shoes and Leather Shoes', 'https://s.alicdn.com/@sc04/kf/H44a5ebd39be5470dbc9e99611c409d8bF.jpg_720x720Q50.jpg', 6425, 7029, 2, 'Spring and Autumn Latest Fashionable Men''s Shoes and Leather Shoes. High-quality product sourced from top Alibaba suppliers. Features premium materials and exceptional durability.', '5 yrs · CN · Jiaozuo Huatong Shoes Factory', 'https://www.alibaba.com/x/1lAevvw?ck=pdp', 'electronics', 'active');
---SQL_END---
